name: setup-pnpm
description: Setup node and pnpm
runs:
  using: composite
  steps:
    - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
      with:
        node-version-file: ".node-version"
        package-manager-cache: false
    - run: npm i -g corepack@latest
      shell: bash
    - run: corepack enable pnpm
      shell: bash
    - id: pnpm-cache
      run: |
        echo "path=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
      shell: bash
    - run: pnpm install
      shell: bash
    - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: ${{ steps.pnpm-cache.outputs.path }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-pnpm-store-
