name: setup-pnpm
description: Setup node and pnpm
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version-file: ".node-version"
    - run: corepack enable pnpm
      shell: bash
    - id: pnpm-cache
      run: |
        echo "path=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
      shell: bash
    - run: pnpm install
      shell: bash
    - uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm-cache.outputs.path }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-pnpm-store-
